name: Soon
options:
  bundleIdPrefix: org.linusu
targets:
  Soon:
    type: application
    platform: iOS
    deploymentTarget: "11.0"
    sources: [Sources]
    settings:
      DEVELOPMENT_TEAM: 8P9699NEPR
    dependencies:
      - carthage: Signals
      - carthage: SnapKit
  # MyFramework:
  #   type: framework
  #   platform: iOS
  #   sources: [MyFramework]
