name: Soon
options:
  bundleIdPrefix: org.linusu
targets:
  Soon:
    type: application
    platform: iOS
    deploymentTarget: "10.0"
    sources: [Sources]
    settings:
      DEVELOPMENT_TEAM: 8P9699NEPR
    # dependencies:
    #   - target: MyFramework
  # MyFramework:
  #   type: framework
  #   platform: iOS
  #   sources: [MyFramework]
